// Generated by scripts/generate.ts from package.json and schemas/*.json. Do not edit.

/** This package's version. */
export const VERSION: string = "0.2.1";

/** The Work Order JSON Schema (schemas/work-order.schema.json). */
export const workOrderSchema: Record<string, unknown> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://awl.dev/schemas/work-order-0.2.json",
  "title": "AWL Work Order v0.2",
  "type": "object",
  "required": [
    "spec",
    "id",
    "created_at",
    "from",
    "to",
    "goal",
    "criteria",
    "budget",
    "deadline",
    "tools"
  ],
  "properties": {
    "spec": {
      "enum": [
        "awl/work-order@0.1",
        "awl/work-order@0.2"
      ]
    },
    "id": {
      "type": "string",
      "minLength": 1,
      "maxLength": 128
    },
    "created_at": {
      "type": "string",
      "format": "date-time"
    },
    "from": {
      "$ref": "#/$defs/agentRef"
    },
    "to": {
      "$ref": "#/$defs/agentRef"
    },
    "goal": {
      "type": "string",
      "minLength": 1
    },
    "criteria": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "id",
          "text"
        ],
        "properties": {
          "id": {
            "type": "string",
            "minLength": 1,
            "maxLength": 64
          },
          "text": {
            "type": "string",
            "minLength": 1
          }
        },
        "additionalProperties": false
      }
    },
    "budget": {
      "$ref": "#/$defs/amounts",
      "minProperties": 1
    },
    "deadline": {
      "type": "string",
      "format": "date-time"
    },
    "tools": {
      "type": "array",
      "items": {
        "$ref": "#/$defs/toolPattern"
      }
    },
    "escalate_to": {
      "$ref": "#/$defs/agentRef"
    },
    "inputs": {
      "type": "object"
    },
    "context": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "uri"
        ],
        "properties": {
          "uri": {
            "type": "string",
            "minLength": 1
          },
          "note": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "handoff": {
      "$ref": "#/$defs/handoff"
    },
    "output_schema": {
      "type": "object"
    },
    "parent_id": {
      "type": "string",
      "minLength": 1
    },
    "metadata": {
      "type": "object"
    }
  },
  "patternProperties": {
    "^x-": {}
  },
  "additionalProperties": false,
  "$defs": {
    "agentRef": {
      "type": "string",
      "minLength": 1,
      "maxLength": 512
    },
    "toolPattern": {
      "type": "string",
      "pattern": "^(\\*|[A-Za-z0-9_.-]+/(\\*|[A-Za-z0-9_.-]+))$"
    },
    "amounts": {
      "type": "object",
      "properties": {
        "usd": {
          "type": "number",
          "minimum": 0
        },
        "tokens": {
          "type": "integer",
          "minimum": 0
        },
        "tool_calls": {
          "type": "integer",
          "minimum": 0
        },
        "seconds": {
          "type": "number",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },
    "handoff": {
      "type": "object",
      "minProperties": 1,
      "properties": {
        "summary": {
          "type": "string",
          "minLength": 1
        },
        "decisions": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "text"
            ],
            "properties": {
              "text": {
                "type": "string",
                "minLength": 1
              },
              "why": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "tried": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "text"
            ],
            "properties": {
              "text": {
                "type": "string",
                "minLength": 1
              },
              "result": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "open_questions": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        },
        "next_step": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    }
  }
};

/** The Work Report JSON Schema (schemas/work-report.schema.json). */
export const workReportSchema: Record<string, unknown> = {
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://awl.dev/schemas/work-report-0.2.json",
  "title": "AWL Work Report v0.2",
  "type": "object",
  "required": [
    "spec",
    "order_id",
    "from",
    "status",
    "result",
    "evidence",
    "cost",
    "finished_at",
    "tools_used"
  ],
  "properties": {
    "spec": {
      "enum": [
        "awl/work-report@0.1",
        "awl/work-report@0.2"
      ]
    },
    "order_id": {
      "type": "string",
      "minLength": 1
    },
    "from": {
      "type": "string",
      "minLength": 1,
      "maxLength": 512
    },
    "status": {
      "enum": [
        "done",
        "blocked",
        "failed"
      ]
    },
    "result": {
      "type": "object",
      "required": [
        "summary"
      ],
      "properties": {
        "summary": {
          "type": "string"
        },
        "output": {},
        "artifacts": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "uri"
            ],
            "properties": {
              "uri": {
                "type": "string",
                "minLength": 1
              },
              "media_type": {
                "type": "string"
              },
              "note": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        }
      },
      "additionalProperties": false
    },
    "evidence": {
      "type": "array",
      "items": {
        "type": "object",
        "required": [
          "criterion",
          "type"
        ],
        "properties": {
          "criterion": {
            "type": "string",
            "minLength": 1
          },
          "type": {
            "enum": [
              "tool_call",
              "artifact",
              "citation",
              "note"
            ]
          },
          "ref": {
            "type": "string"
          },
          "note": {
            "type": "string"
          }
        },
        "additionalProperties": false
      }
    },
    "cost": {
      "type": "object",
      "properties": {
        "usd": {
          "type": "number",
          "minimum": 0
        },
        "tokens": {
          "type": "integer",
          "minimum": 0
        },
        "tool_calls": {
          "type": "integer",
          "minimum": 0
        },
        "seconds": {
          "type": "number",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },
    "started_at": {
      "type": "string",
      "format": "date-time"
    },
    "finished_at": {
      "type": "string",
      "format": "date-time"
    },
    "tools_used": {
      "type": "array",
      "items": {
        "type": "string",
        "pattern": "^[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+$"
      }
    },
    "attempt": {
      "type": "integer",
      "minimum": 1
    },
    "questions": {
      "type": "array",
      "items": {
        "type": "string",
        "minLength": 1
      }
    },
    "error": {
      "type": "string",
      "minLength": 1
    },
    "handoff": {
      "$ref": "#/$defs/handoff"
    },
    "metadata": {
      "type": "object"
    }
  },
  "patternProperties": {
    "^x-": {}
  },
  "additionalProperties": false,
  "$defs": {
    "handoff": {
      "type": "object",
      "minProperties": 1,
      "properties": {
        "summary": {
          "type": "string",
          "minLength": 1
        },
        "decisions": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "text"
            ],
            "properties": {
              "text": {
                "type": "string",
                "minLength": 1
              },
              "why": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "tried": {
          "type": "array",
          "items": {
            "type": "object",
            "required": [
              "text"
            ],
            "properties": {
              "text": {
                "type": "string",
                "minLength": 1
              },
              "result": {
                "type": "string"
              }
            },
            "additionalProperties": false
          }
        },
        "open_questions": {
          "type": "array",
          "items": {
            "type": "string",
            "minLength": 1
          }
        },
        "next_step": {
          "type": "string",
          "minLength": 1
        }
      },
      "additionalProperties": false
    }
  }
};
