name: Feature request
description: Suggest an SDK, CLI or integration feature
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: What do you need to do?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: How might it work?
