// Writes src/generated.ts from schemas/*.json and package.json, so the library needs no
// file reads at runtime and runs outside Node. `--check` fails if the file is out of date.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = new URL("..", import.meta.url);
const read = (path: string) => JSON.parse(readFileSync(new URL(path, root), "utf8"));
const target = fileURLToPath(new URL("src/generated.ts", root));

const source = `// Generated by scripts/generate.ts from package.json and schemas/*.json. Do not edit.

/** This package's version. */
export const VERSION: string = ${JSON.stringify(read("package.json").version)};

/** The Work Order JSON Schema (schemas/work-order.schema.json). */
export const workOrderSchema: Record<string, unknown> = ${JSON.stringify(read("schemas/work-order.schema.json"), null, 2)};

/** The Work Report JSON Schema (schemas/work-report.schema.json). */
export const workReportSchema: Record<string, unknown> = ${JSON.stringify(read("schemas/work-report.schema.json"), null, 2)};
`;

if (process.argv.includes("--check")) {
  let current = "";
  try {
    current = readFileSync(target, "utf8");
  } catch {}
  if (current !== source) {
    console.error("src/generated.ts is out of date. Run: npm run generate");
    process.exit(1);
  }
} else {
  writeFileSync(target, source);
}
